// <auto-generated />
using System;
using HeladeriaAPI.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeladeriaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250704063440_AgregoEntidades")]
    partial class AgregoEntidades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeladeriaAPI.Models.Categoria.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("nombreCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("nombreCategoria")
                        .IsUnique();

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            nombreCategoria = "Frutales"
                        },
                        new
                        {
                            Id = 2,
                            nombreCategoria = "Granizados"
                        },
                        new
                        {
                            Id = 3,
                            nombreCategoria = "Chocolate"
                        },
                        new
                        {
                            Id = 4,
                            nombreCategoria = "Al agua"
                        });
                });

            modelBuilder.Entity("HeladeriaAPI.Models.Estado.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("nombreEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("nombreEstado")
                        .IsUnique();

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            nombreEstado = "Disponible"
                        },
                        new
                        {
                            Id = 2,
                            nombreEstado = "Pendiente"
                        },
                        new
                        {
                            Id = 3,
                            nombreEstado = "No Disponible"
                        });
                });

            modelBuilder.Entity("HeladeriaAPI.Models.Helado.Helado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsArtesanal")
                        .HasColumnType("bit");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<string>("nombreHelado")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("nombreHelado")
                        .IsUnique();

                    b.ToTable("Helados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 2,
                            Descripcion = "Helado de menta con chips de chocolate",
                            EstadoId = 1,
                            FechaCreacion = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArtesanal = false,
                            Precio = 1500.0,
                            nombreHelado = "Menta Granizada"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 3,
                            Descripcion = "Helado de sambayon",
                            EstadoId = 1,
                            FechaCreacion = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArtesanal = false,
                            Precio = 2500.0,
                            nombreHelado = "Sambayon"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            Descripcion = "Helado de pastel de lima",
                            EstadoId = 3,
                            FechaCreacion = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArtesanal = true,
                            Precio = 1000.0,
                            nombreHelado = "Pastel de lima"
                        });
                });

            modelBuilder.Entity("HeladeriaAPI.Models.Ingrediente.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("nombreIngrediente")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("nombreIngrediente")
                        .IsUnique();

                    b.ToTable("Ingredientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            nombreIngrediente = "default"
                        },
                        new
                        {
                            Id = 2,
                            nombreIngrediente = "Leche"
                        },
                        new
                        {
                            Id = 3,
                            nombreIngrediente = "Azucar"
                        },
                        new
                        {
                            Id = 4,
                            nombreIngrediente = "Alcohol"
                        },
                        new
                        {
                            Id = 5,
                            nombreIngrediente = "Chocolate"
                        },
                        new
                        {
                            Id = 6,
                            nombreIngrediente = "Crema"
                        });
                });

            modelBuilder.Entity("HeladeriaAPI.Models.Ingrediente.IngredienteHelado", b =>
                {
                    b.Property<int>("HeladoId")
                        .HasColumnType("int");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int");

                    b.HasKey("HeladoId", "IngredienteId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("IngredienteHelado");
                });

            modelBuilder.Entity("HeladeriaAPI.Models.Helado.Helado", b =>
                {
                    b.HasOne("HeladeriaAPI.Models.Categoria.Categoria", "Categoria")
                        .WithMany("Helados")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeladeriaAPI.Models.Estado.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("HeladeriaAPI.Models.Ingrediente.IngredienteHelado", b =>
                {
                    b.HasOne("HeladeriaAPI.Models.Helado.Helado", null)
                        .WithMany()
                        .HasForeignKey("HeladoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeladeriaAPI.Models.Ingrediente.Ingrediente", null)
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeladeriaAPI.Models.Categoria.Categoria", b =>
                {
                    b.Navigation("Helados");
                });
#pragma warning restore 612, 618
        }
    }
}
